"""Private-workspace access boundary. No public signup or tenant semantics."""

from __future__ import annotations

import asyncio
import hashlib
import hmac
import ipaddress
import json
import secrets
import threading
import time
from collections import deque
from dataclasses import dataclass
from http.cookies import CookieError, SimpleCookie
from urllib.parse import urlsplit
from uuid import uuid4

from .config import Settings

SESSION_SECONDS = 8 * 60 * 60
SCRYPT_PARAMETERS = {"n": 32768, "r": 8, "p": 3, "maxmem": 64 * 1024 * 1024}


def hash_password(password: str) -> str:
    if len(password) < 16 or len(password.encode("utf-8")) > 1024:
        raise ValueError("访问密码至少 16 个字符，最多 1024 UTF-8 字节")
    salt = secrets.token_bytes(16)
    digest = hashlib.scrypt(password.encode("utf-8"), salt=salt, **SCRYPT_PARAMETERS)
    return f"scrypt${salt.hex()}${digest.hex()}"


def _password_parts(encoded: str) -> tuple[bytes, bytes]:
    kind, salt, digest = encoded.split("$")
    if kind != "scrypt" or len(salt) != 32 or len(digest) != 128:
        raise ValueError("invalid password hash")
    return bytes.fromhex(salt), bytes.fromhex(digest)


def validate_access_settings(settings: Settings) -> None:
    if settings.environment not in {"local", "production"}:
        raise ValueError("VERIFIER_ENV must be local or production")
    if settings.environment != "production":
        if settings.password_hash:
            raise ValueError("Password access requires VERIFIER_ENV=production and HTTPS")
        return
    try:
        _password_parts(settings.password_hash)
    except (ValueError, TypeError):
        raise ValueError("Production requires a password hash generated by scripts/hash_password.py") from None
    if not settings.allowed_hosts or any("*" in host or "/" in host or ":" in host for host in settings.allowed_hosts):
        raise ValueError("Production requires explicit VERIFIER_ALLOWED_HOSTS without wildcards or ports")
    if not settings.allowed_origins:
        raise ValueError("Production requires VERIFIER_ALLOWED_ORIGINS")
    for origin in settings.allowed_origins:
        parsed = urlsplit(origin)
        if parsed.scheme != "https" or not parsed.hostname or parsed.username or parsed.password or parsed.query or parsed.fragment or parsed.path:
            raise ValueError("Production origins must be exact HTTPS origins without a trailing slash")
        if parsed.hostname not in settings.allowed_hosts:
            raise ValueError("Production origins must match VERIFIER_ALLOWED_HOSTS")


@dataclass(frozen=True)
class Session:
    csrf: str
    expires: float


class AccessBoundary:
    def __init__(self, app, *, settings: Settings):
        self.app = app
        self.settings = settings
        self.production = settings.environment == "production"
        self.sessions: dict[str, Session] = {}
        self.attempts: deque[float] = deque()
        self.login_lock = threading.Lock()
        self.cookie = "__Host-verifier_session"

    @staticmethod
    async def _json(send, status, data, extra=()):
        body = json.dumps(data, ensure_ascii=False).encode("utf-8")
        await send({"type": "http.response.start", "status": status, "headers": [
            (b"content-type", b"application/json; charset=utf-8"),
            (b"content-length", str(len(body)).encode()), *extra]})
        await send({"type": "http.response.body", "body": body})

    async def _error(self, send, status, code, message, extra=()):
        await self._json(send, status, {"error": {"code": code, "message": message, "request_id": f"r_{uuid4()}"}}, extra)

    def _session(self, headers):
        # Random bearer cookies are only stored as SHA-256 hashes on the server.
        try:
            cookies = SimpleCookie()
            cookies.load(headers.get(b"cookie", b"").decode("latin-1"))
            token = cookies[self.cookie].value
            if len(token) != 64:
                return None, None
        except (KeyError, ValueError, CookieError):
            return None, None
        key = hashlib.sha256(token.encode()).hexdigest()
        session = self.sessions.get(key)
        if session and session.expires > time.monotonic():
            return key, session
        self.sessions.pop(key, None)
        return None, None

    async def __call__(self, scope, receive, send):
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return

        async def secure_send(message):
            if message["type"] == "http.response.start":
                headers = list(message.get("headers", []))
                headers.extend([(b"x-content-type-options", b"nosniff"), (b"referrer-policy", b"no-referrer"),
                                (b"x-frame-options", b"DENY")])
                if scope["path"].startswith("/api/"):
                    headers = [(k, v) for k, v in headers if k.lower() != b"cache-control"]
                    headers.append((b"cache-control", b"no-store"))
                if self.production:
                    headers.append((b"strict-transport-security", b"max-age=31536000"))
                message = {**message, "headers": headers}
            await send(message)

        headers = dict(scope.get("headers", []))
        if self.production and scope.get("scheme") != "https":
            await self._error(secure_send, 400, "HTTPS_REQUIRED", "上线服务仅允许 HTTPS 访问")
            return
        if not self.production:
            client = (scope.get("client") or ("", 0))[0]
            try:
                local = ipaddress.ip_address(client).is_loopback
            except ValueError:
                local = client == "testclient"  # Starlette's in-process tests.
            if not local:
                await self._error(secure_send, 403, "LOCAL_ONLY", "本地模式不接受远程访问，请配置上线模式")
                return

        path = scope["path"]
        if not path.startswith("/api/"):
            await self.app(scope, receive, secure_send)
            return
        if scope["method"] == "OPTIONS":
            await self.app(scope, receive, secure_send)
            return
        unsafe = scope["method"] not in {"GET", "HEAD", "OPTIONS"}
        if unsafe:
            origin = headers.get(b"origin", b"").decode("latin-1")
            if (origin and origin not in self.settings.allowed_origins) or headers.get(b"sec-fetch-site") == b"cross-site":
                await self._error(secure_send, 403, "ORIGIN_REJECTED", "不允许来自其他网站的修改请求")
                return
        if not self.production:
            if path == "/api/auth/session" and scope["method"] == "GET":
                await self._json(secure_send, 200, {"required": False, "authenticated": True, "csrf_token": None})
                return
            await self.app(scope, receive, secure_send)
            return

        key, session = self._session(headers)
        if path == "/api/auth/session" and scope["method"] == "GET":
            await self._json(secure_send, 200, {"required": True, "authenticated": session is not None,
                                              "csrf_token": session.csrf if session else None})
            return
        if path == "/api/auth/login" and scope["method"] == "POST":
            if headers.get(b"x-verifier-request") != b"1":
                await self._error(secure_send, 403, "CSRF_REJECTED", "登录请求缺少安全校验")
                return
            if headers.get(b"content-type", b"").split(b";", 1)[0].strip().lower() != b"application/json":
                await self._error(secure_send, 415, "CONTENT_TYPE_REJECTED", "登录请求必须使用 JSON")
                return
            # Global quota also bounds concurrent expensive password derivations.
            now = time.monotonic()
            with self.login_lock:
                while self.attempts and self.attempts[0] <= now - 60:
                    self.attempts.popleft()
                admitted = len(self.attempts) < 5
                if admitted:
                    self.attempts.append(now)
            if not admitted:
                await self._error(secure_send, 429, "LOGIN_RATE_LIMIT", "登录尝试过于频繁，请一分钟后重试", [(b"retry-after", b"60")])
                return
            raw = bytearray()
            while True:
                message = await receive()
                if message["type"] == "http.disconnect":
                    return
                chunk = message.get("body", b"")
                if len(raw) + len(chunk) > 8192:
                    await self._error(secure_send, 413, "REQUEST_TOO_LARGE", "登录请求过大")
                    return
                raw.extend(chunk)
                if not message.get("more_body", False):
                    break
            try:
                data = json.loads(raw)
                password = data["password"]
                if not isinstance(password, str) or not 16 <= len(password) or len(password.encode()) > 1024:
                    raise ValueError()
            except (ValueError, KeyError, TypeError):
                await self._error(secure_send, 401, "LOGIN_FAILED", "访问密码错误")
                return
            salt, expected = _password_parts(self.settings.password_hash)
            actual = await asyncio.to_thread(hashlib.scrypt, password.encode(), salt=salt, **SCRYPT_PARAMETERS)
            if not hmac.compare_digest(actual, expected):
                await self._error(secure_send, 401, "LOGIN_FAILED", "访问密码错误")
                return
            self.sessions = {k: value for k, value in self.sessions.items() if value.expires > now}
            self.sessions.pop(key, None)
            if len(self.sessions) >= 100:
                await self._error(secure_send, 429, "SESSION_LIMIT", "登录会话数量已达上限，请稍后重试")
                return
            token, csrf = secrets.token_hex(32), secrets.token_hex(32)
            self.sessions[hashlib.sha256(token.encode()).hexdigest()] = Session(csrf, now + SESSION_SECONDS)
            cookie = f"{self.cookie}={token}; Path=/; Max-Age={SESSION_SECONDS}; HttpOnly; Secure; SameSite=Strict".encode()
            await self._json(secure_send, 200, {"required": True, "authenticated": True, "csrf_token": csrf}, [(b"set-cookie", cookie)])
            return
        if not session:
            await self._error(secure_send, 401, "AUTH_REQUIRED", "请先登录后再访问工作区")
            return
        if unsafe and not hmac.compare_digest(headers.get(b"x-csrf-token", b""), session.csrf.encode()):
            await self._error(secure_send, 403, "CSRF_REJECTED", "请求安全校验失效，请重新登录")
            return
        if path == "/api/auth/logout" and scope["method"] == "POST":
            self.sessions.pop(key, None)
            await self._json(secure_send, 200, {"authenticated": False}, [(b"set-cookie", f"{self.cookie}=; Path=/; Max-Age=0; HttpOnly; Secure; SameSite=Strict".encode())])
            return
        await self.app(scope, receive, secure_send)
